client/api.go, client/api_test.go, client/push.go, client/restclient.go, client/search.go
Remove discrete `found` (`bool`) response from `getXXX()` APIs. Instead, return `ErrNotFound`
=> Return ErrNotFound, instead of separate bool return code

client/push.go
This reverts commit 2de08beff4feed1367ef9c21ca39497cc0dc5e29.
With the roll-back of the cloud-library from using the AWS S3 client to
the Minio S3 lib, V2 uploads to an S3 backend fail with a
403. Minio uploads do succeed.
Local testing shows that reverting sending the md5 hash gives working
upload against a local library with both S3 and Minio backends.
If the server-side S3 lib is changed from Minio->AWS in future this may
need to be re-added.
=> Revert "Send md5 metadata header (#54)"

client/push.go, go.mod, go.sum
Remove use of retryable-http module, which requires caching entire file to be uploaded in memory.
Closes #60
=> resolve issue with image uploads on low memory systems

client/client.go, client/client_test.go
Fix bug when a `BaseURL` includes a path component.
Fixes #76
=> Fix BaseURL Path Handling

client/push.go
=> Log multipart abort failure and return original error to caller

client/push.go, client/response.go
Multipart upload start response now includes an "options" field optionally containing field "s3Compliant" to indicate a 100% compliant S3 compatible object store. This PR will omit "X-Amz-Content-Sha256" header on pre-signed PUT URLs based on the option. Default behaviour is to include the header if no option is specified or "s3compliant" is set to `true`, otherwise header is not specified.
Background: AWS SDK for Go source code does not match (omits "X-Amz-Content-Sha256" header) Signature Version 4 documentation that says it's always required. Not all S3 compatible object stores support this header being sent on a multipart upload PUT operation.
=> Disable sha256 checksum header in multipart upload PUTs based on server options

client/push.go
Handle scenario when uploading to cloud library that does not return detailed info on upload completion (single-part or multi-part)
=> Handle upload complete w/o detailed info

client/delete.go, client/delete_test.go
Fixes #104
Library was not recognising the `arch=<value>` parameter as the `=` was being urlencoded:
``
DELETE /v1/images/test/test/test:power?arch%3Damd64
``
=> Do not urlencode the '=' in DeleteImage query string.

.circleci/config.yml
Update `node` to 16.x, and `golangci-lint` to 1.40.x.
=> CI Updates

.circleci/config.yml, .golangci.yml, client/version.go
Update Codecov Orb to latest version. Replace deprecated `golint` linter with `revive`. Address lint found by `revive` linter. Use consistent naming convention (hyphens) in CI config.
=> CI Improvements

.circleci/config.yml, client/client_test.go, client/pull_test.go, client/restclient.go, go.mod
Bump `go.mod` language version to 1.17 to take advantage of [lazy loading](https://golang.org/ref/mod#lazy-loading). Bump CI Go version range to 1.16-1.17. Remove use of deprecated `ioutil` package.
=> Bump Go to 1.17

client/ref.go, client/ref_test.go
Modify `Parse()` and `String()` to remove leading slash from path component of ref.
Closes #134
=> Trim Leading Slash in Ref Paths

client/ref.go, client/ref_test.go
Add `ParseAmbiguous`, which takes into account the Library reference format used by Singularity, which may or may not contain a host portion when a `library://` prefix is used. Add `ParseAmbiguous` unit tests.
=> Add ParseAmbiguous

client/pull.go
This should implement sylabs/scs-library-client#130 and fix sylabs/singularity#698
=> Allow http.Client to handle all redirects except http.StatusSeeOther

client/api.go, client/client.go, client/client_test.go, client/pull.go, client/pull_test.go, client/push.go, client/restclient.go, client/version.go
Also sets `Authorization` header, required for accessing private Sylabs Cloud projects.
Closes #142 , closes #126
=> (Re)use Client.HTTPClient for range requests

.circleci/config.yml, .golangci.yml, client/client.go, client/client_test.go, client/downloader.go, client/downloader_test.go, client/oci.go, client/oci_test.go, client/pull.go, client/pull_test.go, go.mod, go.sum
Implements support for pulling SIF images directly from OCI registry without using Cloud Library as an intermediary.
=> Support for pulling SIF images directly from OCI registry

client/pull.go
Omit "Authorization" header for requests to backend URL provided by Cloud Libary server
=> Fix for specific S3 backends

client/client_test.go, client/downloader.go, client/downloader_test.go, client/pull.go, client/pull_test.go, go.mod
Removes obsolete (Client).DownloadImage() function
- rename `ConcurrentDownloadImage()` to `DownloadImage()`
- rename unexported function `ociDownloadBlobPart` `downloadBlobPart()`
- unit test improvements
=> Remove obsolete DownloadImage() function

client/oci.go, client/oci_test.go
This PR implements client-side support for OCI artifact name mapping
=> Resolve short named artifact issue

client/oci.go, client/pull.go, client/pull_test.go
Add 'mapping=1' to /v1/oci-redirect query string to allow client-side selection of mapping semantics
=> Improved OCI redirect handling

client/client.go, client/oci.go, client/pull.go
Replaces "unexpected HTTP status 401" with "unauthorized" in error returns where HTTP status code is 401
Closes #155
=> Return ErrUnauthorized

client/api.go, client/client.go, client/client_test.go, client/downloader.go, client/oci.go, client/pull.go, client/push.go, client/restclient.go, client/version.go
This PR unexports client attributes that do not need to be exported.
=> Unexport client attributes
